---
provider:
  name: ec2
  virtualization: pvm
  # credentials:
  #   access-key: AFAKEACCESSKEYFORAWS
  #   secret-key: thes3cr3tkeyf0ryourawsaccount/FS4d8Qdva
bootstrapper:
  workspace: /target
image:
  name: debian-{system.release}-{system.architecture}-{provider.virtualization}-{%Y}-{%m}-{%d}-ebs
  description: Debian {system.release} {system.architecture}
system:
  release: unstable
  architecture: amd64
  bootloader: pvgrub
  charmap: UTF-8
  locale: en_US
  timezone: UTC
volume:
  backing: ebs
  partitions:
    type: none
    root:
      filesystem: ext4
      size: 8GiB
packages:
  mirror: http://cloudfront.debian.net/debian
  components:
  - main
  - contrib
  - non-free
plugins:
  cloud_init:
    metadata_sources: Ec2
    username: admin
